/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuU8g2.h"
#include "tcMenuEspAsyncWebServer.h"
#include <IoAbstraction.h>
#include <ArduinoEEPROMAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TcMenuRemoteServer remoteServer;
extern U8G2_SSD1306_128X64_NONAME_F_HW_I2C gfx;
extern GraphicsDeviceRenderer renderer;
extern EspAsyncWebserver webServer;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern ActionMenuItem menuExit;
extern ActionMenuItem menuSaveAll;
extern ActionMenuItem menuClearSettings;
extern BooleanMenuItem menubtn8Push;
extern EnumMenuItem menuLightBtn8;
extern BackMenuItem menuBackButton8;
extern SubMenuItem menuButton8;
extern BooleanMenuItem menubtn7Push;
extern EnumMenuItem menuLightBtn7;
extern BackMenuItem menuBackButton7;
extern SubMenuItem menuButton7;
extern BooleanMenuItem menubtn6Push;
extern EnumMenuItem menuLightBtn6;
extern BackMenuItem menuBackButton6;
extern SubMenuItem menuButton6;
extern BooleanMenuItem menubtn5Push;
extern EnumMenuItem menuLightBtn5;
extern BackMenuItem menuBackButton5;
extern SubMenuItem menuButton5;
extern BooleanMenuItem menubtn4Push;
extern EnumMenuItem menuLightBtn4;
extern BackMenuItem menuBackButton4;
extern SubMenuItem menuButton4;
extern BooleanMenuItem menubtn3Push;
extern EnumMenuItem menuLightBtn3;
extern BackMenuItem menuBackButton3;
extern SubMenuItem menuButton3;
extern BooleanMenuItem menubtn2Push;
extern EnumMenuItem menuLightBtn2;
extern BackMenuItem menuBackButton2;
extern SubMenuItem menuButton2;
extern BooleanMenuItem menubtn1Push;
extern EnumMenuItem menuLightBtn1;
extern BackMenuItem menuBackButton1;
extern SubMenuItem menuButton1;
extern BackMenuItem menuBackButtons;
extern SubMenuItem menuButtons;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuButtons; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION Light(int id);
void CALLBACK_FUNCTION onClearSettings(int id);
void CALLBACK_FUNCTION onExit(int id);
void CALLBACK_FUNCTION onSaveAll(int id);

#endif // MENU_GENERATED_CODE_H
