/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "TCMenu_menu.h"
#include "ThemeMonoBordered.h"

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "SmartPusher", "2f01b637-3a3d-4f52-b7d6-f202ba4f0747" };
TcMenuRemoteServer remoteServer(applicationInfo);
ArduinoEEPROMAbstraction glArduinoEeprom(&EEPROM);
U8G2_SSD1306_128X64_NONAME_F_HW_I2C gfx(U8G2_R0, -1, -1, -1);
U8g2Drawable gfxDrawable(&gfx);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &gfxDrawable);
EspAsyncWebserver webServer("/ws", 80);
EspWebSocketRemoteConnection webClient1(webServer);
EspWebSocketRemoteConnection webClient2(webServer);

// Global Menu Item declarations
const PROGMEM AnyMenuInfo minfoExit = { "Exit", 84, 0xffff, 0, onExit };
ActionMenuItem menuExit(&minfoExit, NULL);
const PROGMEM AnyMenuInfo minfoSaveAll = { "Save all", 83, 0xffff, 0, onSaveAll };
ActionMenuItem menuSaveAll(&minfoSaveAll, &menuExit);
const PROGMEM AnyMenuInfo minfoClearSettings = { "Clear Settings", 81, 0xffff, 0, onClearSettings };
ActionMenuItem menuClearSettings(&minfoClearSettings, &menuSaveAll);
const PROGMEM BooleanMenuInfo minfobtn8Push = { "Pushmode", 75, 202, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menubtn8Push(&minfobtn8Push, false, NULL);
const char enumStrLightBtn8_0[] PROGMEM = "static off";
const char enumStrLightBtn8_1[] PROGMEM = "static on";
const char enumStrLightBtn8_2[] PROGMEM = "breathe";
const char enumStrLightBtn8_3[] PROGMEM = "extern";
const char* const enumStrLightBtn8[] PROGMEM  = { enumStrLightBtn8_0, enumStrLightBtn8_1, enumStrLightBtn8_2, enumStrLightBtn8_3 };
const PROGMEM EnumMenuInfo minfoLightBtn8 = { "Light", 92, 318, 3, Light, enumStrLightBtn8 };
EnumMenuItem menuLightBtn8(&minfoLightBtn8, 0, &menubtn8Push);
RENDERING_CALLBACK_NAME_INVOKE(fnButton8RtCall, backSubItemRenderFn, "Button 8", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButton8 = { "Button 8", 71, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButton8(fnButton8RtCall, &menuLightBtn8);
SubMenuItem menuButton8(&minfoButton8, &menuBackButton8, NULL);
const PROGMEM BooleanMenuInfo minfobtn7Push = { "Pushmode", 69, 197, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menubtn7Push(&minfobtn7Push, false, NULL);
const char enumStrLightBtn7_0[] PROGMEM = "static off";
const char enumStrLightBtn7_1[] PROGMEM = "static on";
const char enumStrLightBtn7_2[] PROGMEM = "breathe";
const char enumStrLightBtn7_3[] PROGMEM = "extern";
const char* const enumStrLightBtn7[] PROGMEM  = { enumStrLightBtn7_0, enumStrLightBtn7_1, enumStrLightBtn7_2, enumStrLightBtn7_3 };
const PROGMEM EnumMenuInfo minfoLightBtn7 = { "Light", 91, 316, 3, Light, enumStrLightBtn7 };
EnumMenuItem menuLightBtn7(&minfoLightBtn7, 0, &menubtn7Push);
RENDERING_CALLBACK_NAME_INVOKE(fnButton7RtCall, backSubItemRenderFn, "Button 7", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButton7 = { "Button 7", 65, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButton7(fnButton7RtCall, &menuLightBtn7);
SubMenuItem menuButton7(&minfoButton7, &menuBackButton7, &menuButton8);
const PROGMEM BooleanMenuInfo minfobtn6Push = { "Pushmode", 63, 192, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menubtn6Push(&minfobtn6Push, false, NULL);
const char enumStrLightBtn6_0[] PROGMEM = "statuc off";
const char enumStrLightBtn6_1[] PROGMEM = "static on";
const char enumStrLightBtn6_2[] PROGMEM = "breathe";
const char enumStrLightBtn6_3[] PROGMEM = "extern";
const char* const enumStrLightBtn6[] PROGMEM  = { enumStrLightBtn6_0, enumStrLightBtn6_1, enumStrLightBtn6_2, enumStrLightBtn6_3 };
const PROGMEM EnumMenuInfo minfoLightBtn6 = { "Light", 90, 314, 3, Light, enumStrLightBtn6 };
EnumMenuItem menuLightBtn6(&minfoLightBtn6, 0, &menubtn6Push);
RENDERING_CALLBACK_NAME_INVOKE(fnButton6RtCall, backSubItemRenderFn, "Button 6", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButton6 = { "Button 6", 59, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButton6(fnButton6RtCall, &menuLightBtn6);
SubMenuItem menuButton6(&minfoButton6, &menuBackButton6, &menuButton7);
const PROGMEM BooleanMenuInfo minfobtn5Push = { "Pushmode", 57, 187, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menubtn5Push(&minfobtn5Push, false, NULL);
const char enumStrLightBtn5_0[] PROGMEM = "static off";
const char enumStrLightBtn5_1[] PROGMEM = "static on";
const char enumStrLightBtn5_2[] PROGMEM = "breathe";
const char enumStrLightBtn5_3[] PROGMEM = "extern";
const char* const enumStrLightBtn5[] PROGMEM  = { enumStrLightBtn5_0, enumStrLightBtn5_1, enumStrLightBtn5_2, enumStrLightBtn5_3 };
const PROGMEM EnumMenuInfo minfoLightBtn5 = { "Light", 89, 312, 3, Light, enumStrLightBtn5 };
EnumMenuItem menuLightBtn5(&minfoLightBtn5, 0, &menubtn5Push);
RENDERING_CALLBACK_NAME_INVOKE(fnButton5RtCall, backSubItemRenderFn, "Button 5", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButton5 = { "Button 5", 53, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButton5(fnButton5RtCall, &menuLightBtn5);
SubMenuItem menuButton5(&minfoButton5, &menuBackButton5, &menuButton6);
const PROGMEM BooleanMenuInfo minfobtn4Push = { "Pushmode", 51, 182, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menubtn4Push(&minfobtn4Push, false, NULL);
const char enumStrLightBtn4_0[] PROGMEM = "static off";
const char enumStrLightBtn4_1[] PROGMEM = "static on";
const char enumStrLightBtn4_2[] PROGMEM = "breathe";
const char enumStrLightBtn4_3[] PROGMEM = "extern";
const char* const enumStrLightBtn4[] PROGMEM  = { enumStrLightBtn4_0, enumStrLightBtn4_1, enumStrLightBtn4_2, enumStrLightBtn4_3 };
const PROGMEM EnumMenuInfo minfoLightBtn4 = { "Light", 88, 310, 3, Light, enumStrLightBtn4 };
EnumMenuItem menuLightBtn4(&minfoLightBtn4, 0, &menubtn4Push);
RENDERING_CALLBACK_NAME_INVOKE(fnButton4RtCall, backSubItemRenderFn, "Button 4", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButton4 = { "Button 4", 47, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButton4(fnButton4RtCall, &menuLightBtn4);
SubMenuItem menuButton4(&minfoButton4, &menuBackButton4, &menuButton5);
const PROGMEM BooleanMenuInfo minfobtn3Push = { "Pushmode", 45, 177, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menubtn3Push(&minfobtn3Push, false, NULL);
const char enumStrLightBtn3_0[] PROGMEM = "static off";
const char enumStrLightBtn3_1[] PROGMEM = "static on";
const char enumStrLightBtn3_2[] PROGMEM = "breathe";
const char enumStrLightBtn3_3[] PROGMEM = "extern";
const char* const enumStrLightBtn3[] PROGMEM  = { enumStrLightBtn3_0, enumStrLightBtn3_1, enumStrLightBtn3_2, enumStrLightBtn3_3 };
const PROGMEM EnumMenuInfo minfoLightBtn3 = { "Light", 87, 308, 3, Light, enumStrLightBtn3 };
EnumMenuItem menuLightBtn3(&minfoLightBtn3, 0, &menubtn3Push);
RENDERING_CALLBACK_NAME_INVOKE(fnButton3RtCall, backSubItemRenderFn, "Button 3", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButton3 = { "Button 3", 41, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButton3(fnButton3RtCall, &menuLightBtn3);
SubMenuItem menuButton3(&minfoButton3, &menuBackButton3, &menuButton4);
const PROGMEM BooleanMenuInfo minfobtn2Push = { "Pushmode", 39, 106, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menubtn2Push(&minfobtn2Push, false, NULL);
const char enumStrLightBtn2_0[] PROGMEM = "static off";
const char enumStrLightBtn2_1[] PROGMEM = "static on";
const char enumStrLightBtn2_2[] PROGMEM = "breathe";
const char enumStrLightBtn2_3[] PROGMEM = "extern";
const char* const enumStrLightBtn2[] PROGMEM  = { enumStrLightBtn2_0, enumStrLightBtn2_1, enumStrLightBtn2_2, enumStrLightBtn2_3 };
const PROGMEM EnumMenuInfo minfoLightBtn2 = { "Light", 86, 306, 3, Light, enumStrLightBtn2 };
EnumMenuItem menuLightBtn2(&minfoLightBtn2, 0, &menubtn2Push);
RENDERING_CALLBACK_NAME_INVOKE(fnButton2RtCall, backSubItemRenderFn, "Button 2", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButton2 = { "Button 2", 35, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButton2(fnButton2RtCall, &menuLightBtn2);
SubMenuItem menuButton2(&minfoButton2, &menuBackButton2, &menuButton3);
const PROGMEM BooleanMenuInfo minfobtn1Push = { "Pushmode", 33, 172, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menubtn1Push(&minfobtn1Push, false, NULL);
const char enumStrLightBtn1_0[] PROGMEM = "static off";
const char enumStrLightBtn1_1[] PROGMEM = "static on";
const char enumStrLightBtn1_2[] PROGMEM = "breathe";
const char enumStrLightBtn1_3[] PROGMEM = "extern";
const char* const enumStrLightBtn1[] PROGMEM  = { enumStrLightBtn1_0, enumStrLightBtn1_1, enumStrLightBtn1_2, enumStrLightBtn1_3 };
const PROGMEM EnumMenuInfo minfoLightBtn1 = { "Light", 85, 304, 3, Light, enumStrLightBtn1 };
EnumMenuItem menuLightBtn1(&minfoLightBtn1, 0, &menubtn1Push);
RENDERING_CALLBACK_NAME_INVOKE(fnButton1RtCall, backSubItemRenderFn, "Button 1", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButton1 = { "Button 1", 14, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButton1(fnButton1RtCall, &menuLightBtn1);
SubMenuItem menuButton1(&minfoButton1, &menuBackButton1, &menuButton2);
RENDERING_CALLBACK_NAME_INVOKE(fnButtonsRtCall, backSubItemRenderFn, "Buttons", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoButtons = { "Buttons", 1, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackButtons(fnButtonsRtCall, &menuButton1);
SubMenuItem menuButtons(&minfoButtons, &menuBackButtons, &menuClearSettings);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    menuMgr.setEepromRef(&glArduinoEeprom);
    // Now add any readonly, non-remote and visible flags.
    menuExit.setLocalOnly(true);

    // Code generated by plugins.
    gfx.begin();
    renderer.setUpdatesPerSecond(10);
    switches.initialise(internalDigitalIo(), true);
    menuMgr.initForUpDownOk(&renderer, &menuButtons, 25, 32, 27);
    remoteServer.addConnection(&webClient1);
    remoteServer.addConnection(&webClient2);
    renderer.setTitleMode(BaseGraphicalRenderer::TITLE_FIRST_ROW);
    renderer.setUseSliderForAnalog(false);
    installMonoBorderedTheme(renderer, MenuFontDef(nullptr, 1), MenuFontDef(nullptr, 1), true);
}

