#define SSID "Kindergarten"
#define password "53825382"
#define MQTThost "blueforcer.de"
#define MQTTport 1883
#define MQTTuser "netplus"
#define MQTTpass "netpluscore"
#define MQTTprefix "SmartPusher"
#define Colonblink true
#define UTCoffset 2